if (( ${+ZIM_HOME} )) zimfw() { source "${HOME}/.config/zim/zimfw.zsh" "${@}" }
fpath=("${HOME}/.config/zim/modules/git/functions" "${HOME}/.config/zim/modules/utility/functions" "${HOME}/.config/zim/modules/duration-info/functions" "${HOME}/.config/zim/modules/git-info/functions" "${HOME}/.config/zim/modules/zaw/functions" "${HOME}/.config/zim/modules/prompt-pwd/functions" "${HOME}/.config/zim/modules/pacman/functions" ${fpath})
autoload -Uz -- git-alias-lookup git-branch-current git-branch-delete-interactive git-branch-remote-tracking git-dir git-ignore-add git-root git-stash-clear-interactive git-stash-recover git-submodule-move git-submodule-remove mkcd mkpw duration-info-precmd duration-info-preexec coalesce git-action git-info fill-vars-or-accept filter-select prompt-pwd
source "${HOME}/.config/zim/modules/environment/init.zsh"
source "${HOME}/.config/zim/modules/git/init.zsh"
source "${HOME}/.config/zim/modules/input/init.zsh"
source "${HOME}/.config/zim/modules/termtitle/init.zsh"
source "${HOME}/.config/zim/modules/utility/init.zsh"
source "${HOME}/.config/zim/modules/duration-info/init.zsh"
source "${HOME}/.config/zim/modules/asciiship/asciiship.zsh-theme"
source "${HOME}/.config/zim/modules/zsh-completions/zsh-completions.plugin.zsh"
source "${HOME}/.config/zim/modules/completion/init.zsh"
source "${HOME}/.config/zim/modules/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "${HOME}/.config/zim/modules/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "${HOME}/.config/zim/modules/zsh-history-substring-search/zsh-history-substring-search.zsh"
source "${HOME}/.config/zim/modules/powerlevel10k/powerlevel10k.zsh-theme"
source "${HOME}/.config/zim/modules/zaw/zaw.zsh"
source "${HOME}/.config/zim/modules/magicmace/magicmace.zsh-theme"
source "${HOME}/.config/zim/modules/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
source "${HOME}/.config/zim/modules/k/k.sh"
source "${HOME}/.config/zim/modules/zsh-autopair/zsh-autopair.plugin.zsh"
source "${HOME}/.config/zim/modules/zfm/zfm.zsh"
source "${HOME}/.config/zim/modules/zsh-z/zsh-z.plugin.zsh"
source "${HOME}/.config/zim/modules/fzf-fasd/fzf-fasd.plugin.zsh"
source "${HOME}/.config/zim/modules/fzf-tab/fzf-tab.zsh"
source "${HOME}/.config/zim/modules/fzf/init.zsh"
source "${HOME}/.config/zim/modules/magic-enter/init.zsh"
source "${HOME}/.config/zim/modules/pacman/init.zsh"
